/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppWorkspaceRouteImport } from './routes/_app/workspace'
import { Route as AppUploadRouteImport } from './routes/_app/upload'
import { Route as AppTutorRouteImport } from './routes/_app/tutor'
import { Route as AppSearchRouteImport } from './routes/_app/search'
import { Route as AppQuizzesRouteImport } from './routes/_app/quizzes'
import { Route as AppFlashcardsRouteImport } from './routes/_app/flashcards'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppAnalyticsRouteImport } from './routes/_app/analytics'
import { Route as AppQuizzesQuizIdRouteImport } from './routes/_app/quizzes.$quizId'
import { Route as AppWorkspaceCourseCourseIdRouteImport } from './routes/_app/workspace/course.$courseId'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorkspaceRoute = AppWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => AppRoute,
} as any)
const AppUploadRoute = AppUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AppRoute,
} as any)
const AppTutorRoute = AppTutorRouteImport.update({
  id: '/tutor',
  path: '/tutor',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppQuizzesRoute = AppQuizzesRouteImport.update({
  id: '/quizzes',
  path: '/quizzes',
  getParentRoute: () => AppRoute,
} as any)
const AppFlashcardsRoute = AppFlashcardsRouteImport.update({
  id: '/flashcards',
  path: '/flashcards',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppQuizzesQuizIdRoute = AppQuizzesQuizIdRouteImport.update({
  id: '/$quizId',
  path: '/$quizId',
  getParentRoute: () => AppQuizzesRoute,
} as any)
const AppWorkspaceCourseCourseIdRoute =
  AppWorkspaceCourseCourseIdRouteImport.update({
    id: '/course/$courseId',
    path: '/course/$courseId',
    getParentRoute: () => AppWorkspaceRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/analytics': typeof AppAnalyticsRoute
  '/dashboard': typeof AppDashboardRoute
  '/flashcards': typeof AppFlashcardsRoute
  '/quizzes': typeof AppQuizzesRouteWithChildren
  '/search': typeof AppSearchRoute
  '/tutor': typeof AppTutorRoute
  '/upload': typeof AppUploadRoute
  '/workspace': typeof AppWorkspaceRouteWithChildren
  '/quizzes/$quizId': typeof AppQuizzesQuizIdRoute
  '/workspace/course/$courseId': typeof AppWorkspaceCourseCourseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/analytics': typeof AppAnalyticsRoute
  '/dashboard': typeof AppDashboardRoute
  '/flashcards': typeof AppFlashcardsRoute
  '/quizzes': typeof AppQuizzesRouteWithChildren
  '/search': typeof AppSearchRoute
  '/tutor': typeof AppTutorRoute
  '/upload': typeof AppUploadRoute
  '/workspace': typeof AppWorkspaceRouteWithChildren
  '/quizzes/$quizId': typeof AppQuizzesQuizIdRoute
  '/workspace/course/$courseId': typeof AppWorkspaceCourseCourseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/flashcards': typeof AppFlashcardsRoute
  '/_app/quizzes': typeof AppQuizzesRouteWithChildren
  '/_app/search': typeof AppSearchRoute
  '/_app/tutor': typeof AppTutorRoute
  '/_app/upload': typeof AppUploadRoute
  '/_app/workspace': typeof AppWorkspaceRouteWithChildren
  '/_app/quizzes/$quizId': typeof AppQuizzesQuizIdRoute
  '/_app/workspace/course/$courseId': typeof AppWorkspaceCourseCourseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/analytics'
    | '/dashboard'
    | '/flashcards'
    | '/quizzes'
    | '/search'
    | '/tutor'
    | '/upload'
    | '/workspace'
    | '/quizzes/$quizId'
    | '/workspace/course/$courseId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/analytics'
    | '/dashboard'
    | '/flashcards'
    | '/quizzes'
    | '/search'
    | '/tutor'
    | '/upload'
    | '/workspace'
    | '/quizzes/$quizId'
    | '/workspace/course/$courseId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/onboarding'
    | '/_app/analytics'
    | '/_app/dashboard'
    | '/_app/flashcards'
    | '/_app/quizzes'
    | '/_app/search'
    | '/_app/tutor'
    | '/_app/upload'
    | '/_app/workspace'
    | '/_app/quizzes/$quizId'
    | '/_app/workspace/course/$courseId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/workspace': {
      id: '/_app/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof AppWorkspaceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/upload': {
      id: '/_app/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof AppUploadRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tutor': {
      id: '/_app/tutor'
      path: '/tutor'
      fullPath: '/tutor'
      preLoaderRoute: typeof AppTutorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/search': {
      id: '/_app/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quizzes': {
      id: '/_app/quizzes'
      path: '/quizzes'
      fullPath: '/quizzes'
      preLoaderRoute: typeof AppQuizzesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/flashcards': {
      id: '/_app/flashcards'
      path: '/flashcards'
      fullPath: '/flashcards'
      preLoaderRoute: typeof AppFlashcardsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quizzes/$quizId': {
      id: '/_app/quizzes/$quizId'
      path: '/$quizId'
      fullPath: '/quizzes/$quizId'
      preLoaderRoute: typeof AppQuizzesQuizIdRouteImport
      parentRoute: typeof AppQuizzesRoute
    }
    '/_app/workspace/course/$courseId': {
      id: '/_app/workspace/course/$courseId'
      path: '/course/$courseId'
      fullPath: '/workspace/course/$courseId'
      preLoaderRoute: typeof AppWorkspaceCourseCourseIdRouteImport
      parentRoute: typeof AppWorkspaceRoute
    }
  }
}

interface AppQuizzesRouteChildren {
  AppQuizzesQuizIdRoute: typeof AppQuizzesQuizIdRoute
}

const AppQuizzesRouteChildren: AppQuizzesRouteChildren = {
  AppQuizzesQuizIdRoute: AppQuizzesQuizIdRoute,
}

const AppQuizzesRouteWithChildren = AppQuizzesRoute._addFileChildren(
  AppQuizzesRouteChildren,
)

interface AppWorkspaceRouteChildren {
  AppWorkspaceCourseCourseIdRoute: typeof AppWorkspaceCourseCourseIdRoute
}

const AppWorkspaceRouteChildren: AppWorkspaceRouteChildren = {
  AppWorkspaceCourseCourseIdRoute: AppWorkspaceCourseCourseIdRoute,
}

const AppWorkspaceRouteWithChildren = AppWorkspaceRoute._addFileChildren(
  AppWorkspaceRouteChildren,
)

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppFlashcardsRoute: typeof AppFlashcardsRoute
  AppQuizzesRoute: typeof AppQuizzesRouteWithChildren
  AppSearchRoute: typeof AppSearchRoute
  AppTutorRoute: typeof AppTutorRoute
  AppUploadRoute: typeof AppUploadRoute
  AppWorkspaceRoute: typeof AppWorkspaceRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppFlashcardsRoute: AppFlashcardsRoute,
  AppQuizzesRoute: AppQuizzesRouteWithChildren,
  AppSearchRoute: AppSearchRoute,
  AppTutorRoute: AppTutorRoute,
  AppUploadRoute: AppUploadRoute,
  AppWorkspaceRoute: AppWorkspaceRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
